name: FallenKingdom
main: com.fk.main.Main
version: 0.4.2
api-version: 1.13
description: Plugin Event FallenKingdom
author: clipsy1
commands:
    fk:
        description: FallenKingdom main menu
        usage: /fk
        aliases:
        - fallenkingdom